### PR TITLE
fix(websub): keep comments and blank lines

### PR DESCRIPTION
**Pull request by jimmy-huang**
Signed-off-by: Jimmy Huang <jimmy.huang@intel.com>

### CODE REVIEW

**Comment by poussa** [comment]
We need this PR. Otherwise the error reporting is way off. Did some testing and seems to work.

LGTM

**Comment by nagineni** [comment]
+1

This is what we are doing for save already in raw mode.

**Comment by jimmy-huang** [comment]
@siovene convIHex is still needed, only stripping out the stripComments() and stripBlankLines() function

**Comment by poussa** [comment]
@siovene let's get this in asap and released to the live site. We need it for hackathon and time is short since we need to test it as well. I can do testing during weekend assuming you can get in in and live.

**Comment by siovene** [comment]
Merged, thanks @jimmy-huang!
@poussa, yes, I can release now.

**Comment by siovene** [comment]
@poussa v0.15.3-alpha released on gh-pages.

**Pull request merged**
