### PR TITLE
webusb: Turn off tansfer commands printing on the console

### PR DESCRIPTION
**Pull request by nagineni**
Use echo mode to turn off transfer commands printing on
the console.

Signed-off-by: Sudarsana Nagineni <sudarsana.nagineni@intel.com>

### CODE REVIEW

**Comment by siovene** [comment]
This PR has linting issue. Can you please take a look?

**Comment by siovene** [comment]
@nagineni, so is this cool to merge even if you run it against a version of `ashell` that doesn't know about `echo_on`/`echo_off`? In other words, does it fail graciously enough?

**Comment by nagineni** [comment]
Okay to merge IMO since it doesn't change the transfer functionality. Everything works same as before expect that we see more logs on the console(like echo_on/echo_off commands are unsupported by ashell) when there is a old version of ashell running in the device.

**Comment by nagineni** [comment]
@brianjjones

**Comment by poussa** [comment]
Tested with the related shell (ZJS) changes. Works well. Can we publish this to live now?

**Comment by siovene** [comment]
Yes, will do :-)

**Comment by siovene** [comment]
I'll first fix https://github.com/01org/zephyrjs-ide/issues/132 and then make a new release, so ETA is soon after lunch.

**Comment by poussa** [comment]
Sounds good.

**Pull request merged**
